### ISSUE TITLE
Use different headings in banner?

### ISSUE THREAD

**Issue by HerrBertling** [beyonk-adventures/gdpr-cookie-consent-banner#1]
Hey 👋 

Thanks for the awesome cookie banner :) Works like a charm with nuxtjs!
I was wondering if the banner's headings should really be `h1`/`h2` – I'm no SEO expert, but these seem a bit "over the top" for me on first inspection.

Would you be open to changing them to e.g. `h3`/`h4`? Or simply a `strong` paragraph and a usual one?

I'd be happy to prepare a pull request 😊

**Comment by antony** [comment]
Hey @HerrBertling - not sure why I'm missing all issues opened on this project!

I believe that a new PR will be opened soon which will rectify some of the styling issues, so hopefully we can fix those tags too.

Sorry it took me so long to reply!

**Comment by mariojankovic** [comment]
Actually I replaced the `h2` with `p` and my guess is that I completely forgot to then update the `h1` to be `h2`. I'll do that right away so we can get that to master as well.

There's a huge discussion on whether a `h1` tag can be anything else than your logo, I'm strongly for it to be reused when a new block-level element has been opened. But most of the sites and linters will scream at you for using `h1` again so we'll stick to the good ol' tradition of avoiding to use it anywhere.

**Comment by HerrBertling** [comment]
Awesome, thanks!
