### ISSUE TITLE
React version?

### ISSUE THREAD

**Issue by ilPas** [beyonk-adventures/gdpr-cookie-consent-banner#11]
Is in roadmap?
Or is there a possibility to use this awesome package with React?

Thanks a lot

**Comment by antony** [comment]
Hi @ilPas 

You can use the package with React by following the Javascript instructions in the README. I'm afraid I don't use React so I can't give any more specific instructions.

**Comment by ilPas** [comment]
I try but i'm not expert, there is an error
`_beyonk_gdpr_cookie_consent_banner__WEBPACK_IMPORTED_MODULE_6___default(...) is not a function`

**Comment by antony** [comment]
Sadly I'm not a React or Webpack user. From what you've listed there, it seems like your webpack configuration isn't quite correct, since the default export of the `esm` bundle is a function called `attachBanner` which is indeed a function.

**Comment by Akiyamka** [comment]
Example with react.
https://codesandbox.io/p/sandbox/gifted-tess-jg7yo1

As I can understand this library just provide some ui for GDPR

**Comment by Vibeesarma** [comment]
is this work for astro.build?

**Comment by antony** [comment]
I've never tried, but yes, it should work with anything.
