### ISSUE TITLE
Provide an example of how a function or event in Configuration would look like

### ISSUE THREAD

**Issue by vedam** [beyonk-adventures/gdpr-cookie-consent-banner#17]
Hi antony,
First of all thanks for this great repo, it really helps me a lot to finally get the GDPR on my site up and running. Providing my own look & feel was a snap. My problem is also less the code from you, but more my lack of understanding of cookies in general (noob-spoiler).

In the readme, under "Configuration", you describe how to create functions for the individual (selected) "categories". Unfortunately it's not clear to me how this config now interacts with the "Banner"-component and the cookie-functions there (setCookie, removeCookie etc.). In the comment you write:

> These are the functions which are run if a user opts-in to that category.
> You should drop your cookies here (or set a variable to control the later dropping of cookies.
> 
> If you are using svelte, you can use events instead - see the Svelte section below.

I use svelte and it would help me a ton if you could possibly provide an example of how such a function or event could look like e.g. for "necessary" maybe setCookie.
Any help appreciated
Thx in advance

**Comment by antony** [comment]
Hey @vedam! Apologies, I should have documented this. I'm going to ping you on discord so I can chat through your requirements since I'm not 100% on them here.

**Comment by vedam** [comment]
Should I close this issue?

**Comment by antony** [comment]
@vedam do you have what you need? if so sure - if not then lets leave it open as a reminder to improve docs.

**Comment by vedam** [comment]
Ups sorry, I forgot this. Yep, everything fine as you described. Cookies are there as soon as site is deployed with correct url.
