### ISSUE TITLE
The configuration is not working as documented.

### ISSUE THREAD

**Issue by inc-ali** [beyonk-adventures/gdpr-cookie-consent-banner#21]
The configuration says:

> If you don't want to show a category, simply remove the specified key from this object.

But removing the key, e.g. `marketing` from the object simply leads to the cookie banner displaying the default values.

To not show the category, e.g. marketing you have to set the value to false, e.g.

`marketing: false`

I can offer a PR, but this is just a one-liner.

**Comment by antony** [comment]
Thanks for your PR!
