### ISSUE TITLE
Suggestion: Icon button do not have an accessible name

### ISSUE THREAD

**Issue by mikeazores** [beyonk-adventures/gdpr-cookie-consent-banner#30]
First of all, thank you for developing this great plugin.

I'm using it on a static site generated with SvelteKit and is working just great.  As it is more important adapt the websites to disabled people, I care a lot my websites to have full score in accessibility area. 

The icon button in this plugin (to manage the cookie settings) fails in accessibility area because it misses the "aria-label" tag. You can [read more on this here](https://web.dev/button-name/?utm_source=lighthouse&utm_medium=lr). 

Is it possible to add this tag to that button? It would also be great that if the "aria-label" would be the same as the settingsLabel prop.

**Comment by antony** [comment]
done!
