### ISSUE TITLE
Missing TypeScript declaration

### ISSUE THREAD

**Issue by cloudlena** [beyonk-adventures/gdpr-cookie-consent-banner#38]
It would be great to get TypeScript typings and a declaration for this package. Currently, I'm getting the following error:

```txt
Could not find a declaration file for module '@beyonk/gdpr-cookie-consent-banner'. '/home/lena/bespinian/bespinian.io-svelte/node_modules/@beyonk/gdpr-cookie-consent-banner/dist/esm/bund
 le.js' implicitly has an 'any' type.
      Try `npm i --save-dev @types/beyonk__gdpr-cookie-consent-banner` if it exists or add a new declaration (.d.ts) file containing `declare module '@beyonk/gdpr-cookie-consent-banner';`
```

The workaround with `declare module '@beyonk/gdpr-cookie-consent-banner';` works but doesn't provide any typings of, for example, the `GdprBanner` Svelte component or its options.

**Comment by antony** [comment]
Closing as I see the PR has been merged - congrats!
